services:
  authz:
    url: http://localhost:8181

bundles:
  risk_policies:
    resource: "/policies/bundle"

decision_logs:
  console: true

status:
  console: true

plugins:
  envoy_ext_authz_grpc:
    addr: :9191
    query: data.risk_aggregation.decision